// BlackRoad Domain Registry — Single source of truth for all domains
// Used by both Cloudflare Functions middleware (SSR/SEO) and React client (routing/branding)

export const DOMAIN_CONFIG = {
  'blackroad.io': {
    id: 'blackroad-io',
    name: 'BlackRoad',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. The operating system for sovereign AI infrastructure. Self-hosted agents, distributed mesh networking, and edge intelligence across a global fleet.',
    landing: 'BlackRoadLanding',
    nav: 'full',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroad.io' },
    routes: 'all',
  },
  'blackroadai.com': {
    id: 'blackroadai',
    name: 'BlackRoad AI',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. 52 TOPS of AI inference on Raspberry Pi clusters with Hailo-8 accelerators. Local models, sovereign compute.',
    landing: 'BlackRoadLanding',
    nav: 'full',
    theme: { accent: '#CC00AA' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadai.com' },
    routes: ['/', '/chat', '/chat2', '/terminal', '/docs', '/status', '/about', '/blog', '/pricing'],
  },
  'blackroad.company': {
    id: 'blackroad-company',
    name: 'BlackRoad OS, Inc.',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Delaware C-Corp building sovereign AI infrastructure. Founded 2024 by Alexa Louise Amundson.',
    landing: 'AboutPage',
    nav: 'minimal',
    theme: { accent: '#FF2255' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroad.company' },
    routes: ['/', '/about', '/leadership', '/blog', '/pricing', '/docs'],
  },
  'blackroad.network': {
    id: 'blackroad-network',
    name: 'BlackRoad Network',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. RoadNet: carrier-grade mesh networking on Raspberry Pi clusters. WireGuard tunnels, Pi-hole DNS, self-healing failover.',
    landing: 'BlackRoadStatus',
    nav: 'minimal',
    theme: { accent: '#00D4FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroad.network' },
    routes: ['/', '/status', '/dashboard', '/docs', '/about'],
  },
  'blackroad.systems': {
    id: 'blackroad-systems',
    name: 'BlackRoad Systems',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Self-healing distributed systems. Docker Swarm, NATS messaging, GitOps pipelines across a 7-node fleet.',
    landing: 'BlackRoadOS',
    nav: 'minimal',
    theme: { accent: '#4488FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroad.systems' },
    routes: ['/', '/os', '/status', '/dashboard', '/explorer', '/docs', '/about'],
  },
  'blackroad.me': {
    id: 'blackroad-me',
    name: 'BlackRoad',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Own your data, own your compute, own your identity.',
    landing: 'BlackRoadAuth',
    nav: 'minimal',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'WebApplication', canonical: 'https://blackroad.me' },
    routes: ['/', '/auth', '/settings', '/onboarding'],
  },
  'blackroadinc.us': {
    id: 'blackroadinc',
    name: 'BlackRoad Inc.',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Sovereign computing infrastructure company. Delaware C-Corp, est. 2024.',
    landing: 'AboutPage',
    nav: 'minimal',
    theme: { accent: '#FF2255' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadinc.us' },
    routes: ['/', '/about', '/leadership', '/pricing'],
  },
  'lucidia.earth': {
    id: 'lucidia-earth',
    name: 'Lucidia',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Lucidia: autonomous AI agent with persistent memory, cognition, and creative intelligence.',
    landing: 'LucidiaTerminal',
    nav: 'minimal',
    theme: { accent: '#CC00AA' },
    seo: { ogType: 'website', jsonLdType: 'SoftwareApplication', canonical: 'https://lucidia.earth' },
    routes: ['/', '/terminal', '/chat', '/chat2', '/docs', '/about'],
  },
  'lucidia.studio': {
    id: 'lucidia-studio',
    name: 'Lucidia Studio',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Lucidia Studio: AI-powered creative workspace for code, writing, and design.',
    landing: 'LucidiaTerminal',
    nav: 'minimal',
    theme: { accent: '#CC00AA' },
    seo: { ogType: 'website', jsonLdType: 'SoftwareApplication', canonical: 'https://lucidia.studio' },
    routes: ['/', '/terminal', '/chat', '/command', '/docs'],
  },
  'lucidiaqi.com': {
    id: 'lucidiaqi',
    name: 'Lucidia QI',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Lucidia QI: quantum-inspired intelligence engine. Mathematical foundations for autonomous reasoning.',
    landing: 'LucidiaTerminal',
    nav: 'minimal',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'SoftwareApplication', canonical: 'https://lucidiaqi.com' },
    routes: ['/', '/terminal', '/chat', '/docs', '/about'],
  },
  'aliceqi.com': {
    id: 'aliceqi',
    name: 'Alice QI',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Alice QI: the gateway node. DNS, routing, Pi-hole, and edge intelligence at the network perimeter.',
    landing: 'BlackRoadDashboard',
    nav: 'minimal',
    theme: { accent: '#FF6B2B' },
    seo: { ogType: 'website', jsonLdType: 'SoftwareApplication', canonical: 'https://aliceqi.com' },
    routes: ['/', '/dashboard', '/status', '/docs'],
  },
  'blackroadqi.com': {
    id: 'blackroadqi',
    name: 'BlackRoad QI',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. BlackRoad QI: quantum-inspired computing platform. 317+ equations, mathematical infrastructure for sovereign AI.',
    landing: 'BlackRoadLanding',
    nav: 'minimal',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadqi.com' },
    routes: ['/', '/docs', '/about', '/blog'],
  },
  'roadcoin.io': {
    id: 'roadcoin',
    name: 'RoadCoin',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. RoadCoin: compute credits for the BlackRoad mesh network. Pay for inference, earn by contributing nodes.',
    landing: 'BlackRoadPricing',
    nav: 'minimal',
    theme: { accent: '#FF6B2B' },
    seo: { ogType: 'website', jsonLdType: 'WebApplication', canonical: 'https://roadcoin.io' },
    routes: ['/', '/pricing', '/docs', '/about'],
  },
  'blackroadquantum.store': {
    id: 'blackroadquantum-store',
    name: 'BlackRoad Quantum',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Sovereign AI hardware kits. Pre-configured Raspberry Pi clusters with Hailo-8 accelerators.',
    landing: 'BlackRoadPricing',
    nav: 'minimal',
    theme: { accent: '#00D4FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadquantum.store' },
    routes: ['/', '/pricing', '/docs', '/about'],
  },
  'blackroadquantum.com': {
    id: 'blackroadquantum-com',
    name: 'BlackRoad Quantum',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Quantum-inspired AI computing. Hardware accelerators, mathematical foundations, sovereign infrastructure.',
    landing: 'BlackRoadLanding',
    nav: 'minimal',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadquantum.com' },
    routes: ['/', '/pricing', '/docs', '/about'],
  },
  'blackroadquantum.net': {
    id: 'blackroadquantum-net',
    name: 'BlackRoad Quantum',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Distributed quantum-inspired computing network. 52 TOPS across sovereign edge nodes.',
    landing: 'BlackRoadStatus',
    nav: 'minimal',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadquantum.net' },
    routes: ['/', '/status', '/docs', '/about'],
  },
  'blackroadquantum.info': {
    id: 'blackroadquantum-info',
    name: 'BlackRoad Quantum',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Research and documentation for quantum-inspired AI infrastructure.',
    landing: 'BlackRoadDocs',
    nav: 'minimal',
    theme: { accent: '#8844FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadquantum.info' },
    routes: ['/', '/docs', '/blog', '/about'],
  },
  'blackroadquantum.shop': {
    id: 'blackroadquantum-shop',
    name: 'BlackRoad Quantum Shop',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Sovereign AI hardware kits, Hailo-8 accelerators, pre-configured Pi clusters.',
    landing: 'BlackRoadPricing',
    nav: 'minimal',
    theme: { accent: '#FF6B2B' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackroadquantum.shop' },
    routes: ['/', '/pricing', '/docs', '/about'],
  },
  'roadchain.io': {
    id: 'roadchain',
    name: 'RoadChain',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. RoadChain: distributed ledger for sovereign compute. Proof-of-inference, node attestation, verifiable AI.',
    landing: 'RoadChainExplorer',
    nav: 'minimal',
    theme: { accent: '#00D4FF' },
    seo: { ogType: 'website', jsonLdType: 'WebApplication', canonical: 'https://roadchain.io' },
    routes: ['/', '/chain', '/docs', '/about', '/pricing'],
  },
  'blackboxprogramming.io': {
    id: 'blackboxprogramming',
    name: 'Blackbox Programming',
    tagline: 'Pave Tomorrow.',
    description: 'BlackRoad OS — Pave Tomorrow. Open-source tools, SDKs, and developer infrastructure for sovereign computing.',
    landing: 'BlackRoadDocs',
    nav: 'minimal',
    theme: { accent: '#4488FF' },
    seo: { ogType: 'website', jsonLdType: 'Organization', canonical: 'https://blackboxprogramming.io' },
    routes: ['/', '/docs', '/explorer', '/chain', '/blog', '/about'],
  },
};

export const DEFAULT_DOMAIN = 'blackroad.io';

export function getDomainConfig(hostname) {
  const clean = hostname.replace(/:\d+$/, '').replace(/^www\./, '');
  return DOMAIN_CONFIG[clean] || DOMAIN_CONFIG[DEFAULT_DOMAIN];
}
